import { z } from 'zod'

export const extensionImportSchema = z.object({
  zillowUrl: z.string().url(),
  extractedData: z.object({
    address: z.string().nullable().optional(),
    city: z.string().nullable().optional(),
    state: z.string().nullable().optional(),
    zip: z.string().nullable().optional(),
    propertyType: z.string().nullable().optional(),
    beds: z.union([z.number().int().min(0), z.null()]).optional(),
    baths: z.union([z.number().min(0), z.null()]).optional(),
    sqft: z.union([z.number().int().positive(), z.null()]).optional(),
    yearBuilt: z.union([z.number().int().min(1800).max(2100), z.null()]).optional(),
    listPrice: z.union([z.number().positive(), z.null()]).optional(),
    hoaMonthly: z.union([z.number().min(0), z.null()]).optional(),
    taxesAnnual: z.union([z.number().min(0), z.null()]).optional(),
  }),
  importedFields: z.array(z.string()),
  missingFields: z.array(z.string()),
  fieldConfidences: z.record(z.string(), z.number().min(0).max(1)).optional().default({}),
  extractorVersion: z.enum(['structured_v1', 'semantic_v1', 'regex_v1', 'sidebar_v1']),
  purchaseType: z.enum(['primary_residence', 'investment_property', 'house_hack', 'vacation_home', 'other']),
  downPaymentPct: z.number().min(0).max(100),
})

export const createDealSchema = z.object({
  address: z.string().optional(),
  purchasePrice: z.number().positive().optional(),
  rentMonthly: z.number().min(0).optional(),
  taxesAnnual: z.number().min(0).optional(),
  insuranceAnnual: z.number().min(0).optional(),
  interestRate: z.number().min(0).max(100).optional(),
  downPaymentPct: z.number().min(0).max(100).optional(),
  termYears: z.number().int().min(1).max(50).optional(),
})

export const updateDealSchema = z.object({
  zillowUrl: z.string().url().nullable().optional(),
  address: z.string().nullable().optional(),
  city: z.string().nullable().optional(),
  state: z.string().nullable().optional(),
  zip: z.string().nullable().optional(),
  propertyType: z.string().nullable().optional(),
  beds: z.number().int().min(0).nullable().optional(),
  baths: z.number().min(0).nullable().optional(),
  sqft: z.number().int().positive().nullable().optional(),
  yearBuilt: z.number().int().min(1800).max(2100).nullable().optional(),
  listPrice: z.number().positive().nullable().optional(),
  hoaMonthly: z.number().min(0).nullable().optional(),
  taxesAnnual: z.number().min(0).nullable().optional(),
  purchaseType: z.enum(['primary_residence', 'investment_property', 'house_hack', 'vacation_home', 'other']).nullable().optional(),
  purchasePrice: z.number().positive().nullable().optional(),
  closingCostRate: z.number().min(0).max(100).nullable().optional(),
  rehabCost: z.number().min(0).nullable().optional(),
  downPaymentPct: z.number().min(0).max(100).nullable().optional(),
  interestRate: z.number().min(0).max(100).nullable().optional(),
  termYears: z.number().int().min(1).max(50).nullable().optional(),
  pmiEnabled: z.boolean().optional(),
  pmiMonthly: z.number().min(0).nullable().optional(),
  insuranceAnnual: z.number().min(0).nullable().optional(),
  utilitiesMonthly: z.number().min(0).nullable().optional(),
  rentMonthly: z.number().min(0).nullable().optional(),
  otherIncomeMonthly: z.number().min(0).nullable().optional(),
  vacancyRate: z.number().min(0).max(100).nullable().optional(),
  maintenanceRate: z.number().min(0).max(100).nullable().optional(),
  capexRate: z.number().min(0).max(100).nullable().optional(),
  managementRate: z.number().min(0).max(100).nullable().optional(),
  numberOfUnits: z.number().int().min(1).max(20).nullable().optional(),
  rentPerUnit: z.number().min(0).nullable().optional(),
  vacancyRatePerUnit: z.number().min(0).max(100).nullable().optional(),
  // Holding period projection inputs
  holdingPeriodYears: z.number().int().min(1).max(30).nullable().optional(),
  appreciationRate: z.number().min(-20).max(20).nullable().optional(),
  rentGrowthRate: z.number().min(-10).max(20).nullable().optional(),
  expenseGrowthRate: z.number().min(-10).max(20).nullable().optional(),
  sellingCostRate: z.number().min(0).max(20).nullable().optional(),
  notes: z.string().nullable().optional(),
})

export const analyzeDealSchema = z.object({
  purchasePrice: z.number().positive(),
  closingCostRate: z.number().min(0).max(100),
  rehabCost: z.number().min(0),
  downPaymentPct: z.number().min(0).max(100),
  interestRate: z.number().min(0).max(100),
  termYears: z.number().int().min(1).max(50),
  pmiEnabled: z.boolean(),
  pmiMonthly: z.number().min(0),
  taxesAnnual: z.number().min(0),
  insuranceAnnual: z.number().min(0),
  hoaMonthly: z.number().min(0),
  utilitiesMonthly: z.number().min(0),
  rentMonthly: z.number().min(0),
  otherIncomeMonthly: z.number().min(0),
  vacancyRate: z.number().min(0).max(100),
  maintenanceRate: z.number().min(0).max(100),
  capexRate: z.number().min(0).max(100),
  managementRate: z.number().min(0).max(100),
  // Holding period projection inputs
  holdingPeriodYears: z.number().int().min(1).max(30).optional(),
  appreciationRate: z.number().min(-20).max(20).optional(),
  rentGrowthRate: z.number().min(-10).max(20).optional(),
  expenseGrowthRate: z.number().min(-10).max(20).optional(),
  sellingCostRate: z.number().min(0).max(20).optional(),
})
