#!/usr/bin/env node

/**
 * This script generates a secrets config file during the Amplify build.
 * The secrets come from Amplify Console environment variables.
 * This file is gitignored and regenerated on each deployment.
 */

const fs = require('fs');
const path = require('path');

// Debug: list all env vars that contain SUPABASE
console.log('=== Debug: Searching for SUPABASE env vars ===');
Object.keys(process.env).filter(k => k.includes('SUPABASE')).forEach(k => {
  console.log(`  ${k}: ${process.env[k] ? 'SET (length: ' + process.env[k].length + ')' : 'NOT SET'}`);
});

const secrets = {
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY || '',
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY || '',
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET || '',
  STRIPE_PRO_PRICE_ID: process.env.STRIPE_PRO_PRICE_ID || '',
};

const content = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/generate-secrets.js during build

export const GENERATED_SECRETS = {
  SUPABASE_SERVICE_ROLE_KEY: '${secrets.SUPABASE_SERVICE_ROLE_KEY}',
  STRIPE_SECRET_KEY: '${secrets.STRIPE_SECRET_KEY}',
  STRIPE_WEBHOOK_SECRET: '${secrets.STRIPE_WEBHOOK_SECRET}',
  STRIPE_PRO_PRICE_ID: '${secrets.STRIPE_PRO_PRICE_ID}',
};
`;

const outputPath = path.join(__dirname, '..', 'lib', 'generated-secrets.ts');

fs.writeFileSync(outputPath, content, 'utf-8');

console.log('✓ Generated lib/generated-secrets.ts');
console.log('  SUPABASE_SERVICE_ROLE_KEY:', secrets.SUPABASE_SERVICE_ROLE_KEY ? 'SET' : 'NOT SET');
console.log('  STRIPE_SECRET_KEY:', secrets.STRIPE_SECRET_KEY ? 'SET' : 'NOT SET');
console.log('  STRIPE_WEBHOOK_SECRET:', secrets.STRIPE_WEBHOOK_SECRET ? 'SET' : 'NOT SET');
console.log('  STRIPE_PRO_PRICE_ID:', secrets.STRIPE_PRO_PRICE_ID ? 'SET' : 'NOT SET');
